export const pingResponses = {
  unexpected_phrases: [
    "🏓 PONG? Eu prefiro pão com ovo.",
    "Você piscou. Eu respondi.",
    "Ping? Aqui é o Rei do Delay 👑",
    "⏱️ Estou medindo a velocidade da luz... quase lá.",
    "Servidor respondeu com um suspiro... 💨",
    "🏃 Correndo atrás do servidor, aguarde...",
    "Ping recebido. Confirme com um 'pong'.",
    "📡 Comunicação iniciada com a nave-mãe.",
    "Eu senti esse ping na alma...",
    "👀 O ping te observou de volta.",
    "🚀 Ping enviado para Marte... aguardando resposta.",
    "Este ping foi patrocinado por ninguém.",
    "🧠 Pensando... pensando... pronto!",
    "🌐 Conectando ao universo paralelo...",
    "🔍 Procurando respostas existenciais...",
    "📦 Ping embrulhado e enviado via Sedex.",
    "🦦 Um ping, um som, uma jornada.",
    "📉 Latência abaixo do nível do mar.",
    "🐌 Ping modo lesma ativado.",
    "⚙️ Girando engrenagens... ping completo.",
  ],
  random_facts: [
    "Os flamingos nascem cinza.",
    "O som do trovão pode ser ouvido a mais de 25km de distância.",
    "Um polvo tem três corações.",
    "Abacaxis demoram dois anos para crescer.",
    "O ponto preto no centro de um CD é só decoração.",
    "Alguns peixes podem andar fora d'água por horas.",
    "A Lua se afasta da Terra 3,8cm por ano.",
    "Um raio é cinco vezes mais quente que a superfície do Sol.",
    "O primeiro e-mail foi enviado em 1971.",
    "As formigas não dormem.",
    "O cérebro humano consome cerca de 20% da nossa energia.",
    "As borboletas sentem o gosto com os pés.",
    "Camelos têm três pálpebras para se proteger da areia.",
    "Existem mais estrelas no universo do que grãos de areia na Terra.",
    "Golfinhos dormem com um olho aberto.",
    "A Torre Eiffel pode crescer até 15cm no verão.",
    "Os morcegos sempre viram à esquerda ao sair de uma caverna.",
    "Pinguins têm joelhos escondidos sob as penas.",
    "O som viaja mais rápido na água do que no ar.",
    "A Terra não é perfeitamente redonda, é ligeiramente achatada nos polos.",
  ],
  short_jokes: [
    "Por que o bot atravessou a API? Pra chegar do outro lado!",
    "Quantos devs precisa pra trocar uma lâmpada? Nenhum, é problema do front.",
    "Usei console.log no deserto e ninguém viu.",
    "Bati no servidor... agora ele só responde 500.",
    "Java e café: os dois te mantêm acordado, mas só um compila.",
    "O que o JavaScript disse pro JSON? 'Você tem estilo!'",
    "Desenvolvedor é tipo mágico: faz bug sumir e aparecer de novo.",
    "A vida é um loop infinito até o break.",
    "Meu ping é tão rápido que chega antes do comando.",
    "Comi tanto bug que virei QA.",
    "Fiz deploy e o sistema sumiu. Feature ou bug?",
    "O commit era final, mas voltou com mudanças.",
    "Front-end sem CSS é tipo bolo sem cobertura.",
    "Fui tomar um café e encontrei outro bug.",
    "Backup é igual seguro: só lembra quando dá ruim.",
    "Pinguei tanto que virei sonar.",
    "Botei o código pra rodar, ele correu.",
    "Debugando até os sonhos.",
    "Versão estável: até alguém usar.",
    "404: piada não encontrada.",
  ],
};
