export const pingResponses = {
  unexpected_phrases: [
    "🏓 PONG? Eu prefiro pão com ovo.",
    "Você piscou. Eu respondi.",
    "Ping? Aqui é o Rei do Delay 👑",
    "⏱️ Estou medindo a velocidade da luz... quase lá.",
    "Servidor respondeu com um suspiro... 💨",
    "🏃 Correndo atrás do servidor, aguarde...",
    "Ping recebido. Confirme com um 'pong'.",
    "📡 Comunicação iniciada com a nave-mãe.",
    "Eu senti esse ping na alma...",
    "👀 O ping te observou de volta.",
    "🚀 Ping enviado para Marte... aguardando resposta.",
    "Este ping foi patrocinado por ninguém.",
    "🧠 Pensando... pensando... pronto!",
    "🌐 Conectando ao universo paralelo...",
    "🔍 Procurando respostas existenciais...",
    "📦 Ping embrulhado e enviado via Sedex.",
    "🦦 Um ping, um som, uma jornada.",
    "📉 Latência abaixo do nível do mar.",
    "🐌 Ping modo lesma ativado.",
    "⚙️ Girando engrenagens... ping completo.",
    "Ping? Só se for com café.",
    "🏓 PONG! Mas só depois do almoço.",
    "Ping enviado... resposta perdida no espaço.",
    "📡 Tentando conexão com o passado...",
    "Ping? Parece mais um eco no vazio.",
    "⏳ Processando... ainda processando...",
    "Ping recebido, mas não esperado.",
    "🎲 Jogando dados para decidir a resposta...",
    "Ping? Aqui é o mestre dos tempos de resposta.",
    "🌀 Ping perdido no multiverso.",
  ],
  random_facts: [
    "Os flamingos nascem cinza.",
    "O som do trovão pode ser ouvido a mais de 25km de distância.",
    "Um polvo tem três corações.",
    "Abacaxis demoram dois anos para crescer.",
    "O ponto preto no centro de um CD é só decoração.",
    "Alguns peixes podem andar fora d'água por horas.",
    "A Lua se afasta da Terra 3,8cm por ano.",
    "Um raio é cinco vezes mais quente que a superfície do Sol.",
    "O primeiro e-mail foi enviado em 1971.",
    "As formigas não dormem.",
    "O cérebro humano consome cerca de 20% da nossa energia.",
    "As borboletas sentem o gosto com os pés.",
    "Camelos têm três pálpebras para se proteger da areia.",
    "Existem mais estrelas no universo do que grãos de areia na Terra.",
    "Golfinhos dormem com um olho aberto.",
    "A Torre Eiffel pode crescer até 15cm no verão.",
    "Os morcegos sempre viram à esquerda ao sair de uma caverna.",
    "Pinguins têm joelhos escondidos sob as penas.",
    "O som viaja mais rápido na água do que no ar.",
    "A Terra não é perfeitamente redonda, é ligeiramente achatada nos polos.",
    "As zebras são pretas com listras brancas.",
    "O coração de uma baleia azul pode pesar até 180kg.",
    "As bananas são tecnicamente classificadas como bagas.",
    "O maior deserto do mundo é a Antártida.",
    "As aranhas podem produzir até sete tipos diferentes de seda.",
    "O Monte Everest cresce cerca de 4mm por ano.",
    "Os gatos têm 32 músculos em cada orelha.",
    "A água-viva não tem cérebro nem coração.",
    "O sangue dos caranguejos-ferradura é azul.",
    "O maior organismo vivo é um fungo no Oregon, EUA.",
  ],
  short_jokes: [
    "Por que o bot atravessou a API? Pra chegar do outro lado!",
    "Quantos devs precisa pra trocar uma lâmpada? Nenhum, é problema do front.",
    "Usei console.log no deserto e ninguém viu.",
    "Bati no servidor... agora ele só responde 500.",
    "Java e café: os dois te mantêm acordado, mas só um compila.",
    "O que o JavaScript disse pro JSON? 'Você tem estilo!'",
    "Desenvolvedor é tipo mágico: faz bug sumir e aparecer de novo.",
    "A vida é um loop infinito até o break.",
    "Meu ping é tão rápido que chega antes do comando.",
    "Comi tanto bug que virei QA.",
    "Fiz deploy e o sistema sumiu. Feature ou bug?",
    "O commit era final, mas voltou com mudanças.",
    "Front-end sem CSS é tipo bolo sem cobertura.",
    "Fui tomar um café e encontrei outro bug.",
    "Backup é igual seguro: só lembra quando dá ruim.",
    "Pinguei tanto que virei sonar.",
    "Botei o código pra rodar, ele correu.",
    "Debugando até os sonhos.",
    "Versão estável: até alguém usar.",
    "404: piada não encontrada.",
    "Por que o dev foi ao psicólogo? Para tratar seus loops infinitos.",
    "O que o HTML disse para o CSS? 'Você me dá estilo!'",
    "Fiz um ping tão rápido que o servidor ficou com inveja.",
    "Por que o código foi ao médico? Porque estava com muitos bugs.",
    "O que o Python disse para o Java? 'Você é muito rígido!'",
    "Deploy sem teste é igual pular sem paraquedas.",
    "O servidor está tão lento que virou museu.",
    "Debug é como detetive: sempre procurando pistas.",
    "Por que o dev não usa escada? Prefere subir em loops.",
    "404: humor não encontrado.",
  ],
};
